### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by nutinshell** [davidmurray/wifi#1]
Log's here: http://d.pr/f/Di7W

**Comment by davidmurray** [comment]
Hm, interesting.

Is WiFi on? ;P

**Comment by nutinshell** [comment]
Sure.. :)

**Comment by davidmurray** [comment]
I'll investigate more later this week as I am on vacation right now.

**Comment by davidmurray** [comment]
Is there anything interesting in the syslog?

**Comment by nutinshell** [comment]
Something like:
<Error>: WiFi:[399313983.480678]: WiFi unquiescing requested by "locationd"
<Error>: WiFi:[399313992.598467]: kern_return_t _wifi_manager_open(mach_port_t, int, int, mach_port_t, mach_port_t *, audit_token_t) Client WiFi has no entitlement
WiFi:[399313992.599504]: Failed to open connection to WiFi Manager kr=2
<Notice>: Formulating crash report for process WiFi[25052]

**Comment by davidmurray** [comment]
OK, can you run  `ldid -e /Applications/WiFi.app/WiFi` on your device and tell me what it outputs?

Thanks

**Comment by nutinshell** [comment]
Opps, does it req jailbreak? I don't jailbreak my device..

**Comment by davidmurray** [comment]
Then how did...you...try this application? O_O

**Comment by nutinshell** [comment]
make and then codesign it with my dev cert, install it with Xcode :)

**Comment by davidmurray** [comment]
I doubt that'll work. You need to jailbreak and use ldid, theos, etc.

**Comment by theiostream** [comment]
technically he can set that entitlement with xcode, and ldid is technically not an iphone-only tool :P (therefore he can add entitlements in his mac or even as an xcode build step)

**Comment by davidmurray** [comment]
I don't think Xcode will allow it though. Build the app, package it and then resign it with ldid.
