### ISSUE TITLE
Can't configure your project

### ISSUE THREAD

**Issue by skywinder** [davidmurray/wifi#11]
Hello. 
I try to install your project. https://github.com/Cykey/wifi

But there is a first time, when I work with makefile in iOs project.

Can you help me, how to build this project?
I try to run `make`.
but got this error:

`git submodule update --init --recursive`

> Cloning into 'ios-reversed-headers'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:Cykey/ios-reversed-headers.git' into submodule path 'ios-reversed-headers' failed
> make: **\* [all] Error 1

The command
`git clone --recursive https://github.com/Cykey/wifi.git`
get the same error:

> Fatal: Could not read from remote repository.
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:Cykey/ios-reversed-headers.git' into submodule path 'ios-reversed-headers' failed
> make: **\* [all] Error 1

Can you help me to fix it?

**Comment by davidmurray** [comment]
I responded via e-mail.

**Comment by skywinder** [comment]
Thank you for quick response.
I just copy your response here in case, if someone will have same problem:

> You need to set up your public key on github.

https://help.github.com/articles/generating-ssh-keys

It works, thanks.
