### ISSUE TITLE
Hey, I don't jailbreak my device，Can I use the MobileWiFi.framework?

### ISSUE THREAD

**Issue by ligang2495** [davidmurray/wifi#15]
Hey, I don't jailbreak my device，Can I use the MobileWiFi.framework?

**Comment by davidmurray** [comment]
Yes, but not in an App Store app. Apple won't allow it.

**Comment by ligang2495** [comment]
Thanks.

**Comment by JsJenny** [comment]
No I tried using Xcode6 and IOS8 and cannot get it to work. Here is what I found on stackoverflow "http://stackoverflow.com/questions/18654113/access-private-apis-on-non-jailbroken-devices-for-business-use-only" can you please let me know if it is possible, I was trying to get this work from 2 days and no luck.

**Comment by davidmurray** [comment]
I don't think it's possible if you are trying to sign your app with a provisioning profile.
