### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by santhuisland** [davidmurray/wifi#19]
Hi,

i have downloaded this full folder,
can you please tell me how to compile in this project in XCode, i can't find any project file in folder.

Thanks
Santhosh

**Comment by davidmurray** [comment]
You need to compile it with [theos](http://github.com/DHowett/theos).
See [this](http://iphonedevwiki.net/index.php/Theos/Setup) setup page for more information.

**Comment by santhuisland** [comment]
Hi All,

Advance thanks for your help..
i am really want to fix this in my project. Please please help me

1)My application will not go to Appstore, it will be Enterprice app.
2)I want to trigger wifi scan programatically, nothing else.
3)where i can find private framework "MobileWiFi.framework" in Xcode 6.1?
4)I have included "WiFiDeviceClient.h,WiFiNetwork.h,WiFiManager.h,MobileWiFi.h"
5)I have include Entitlement.plist same has downloaded from this project. But getting following error 
"The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. (0xE8008016)."
6)I need to jailbroke the device?
5) using following code
                _manager = WiFiManagerClientCreate(kCFAllocatorDefault, 0);
        CFArrayRef devices = WiFiManagerClientCopyDevices(_manager);
        if (devices) {
            _client = (WiFiDeviceClientRef)CFArrayGetValueAtIndex(devices, 0);
            CFRetain(_client);
            CFRelease(devices);
        }
        _networks = [[NSMutableArray alloc] init];
WiFiManagerClientScheduleWithRunLoop(_manager, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);
    WiFiDeviceClientScanAsync(_client, (CFDictionaryRef)[NSDictionary dictionary], DMScanCallback, NULL);

Thanks
Santhosh

**Comment by davidmurray** [comment]
OK, well first of all, you won't be able to make an enterprise app (with provisioning) that uses MobileWiFi.framework. It is impossible; I have tried.

**Comment by santhuisland** [comment]
i can use Enterprice distribution profile.
but need to jail break the device to install? ,my app always stay in installing when i sync with itunes.

Thanks
Santhosh

**Comment by davidmurray** [comment]
Jailbreaking the device would certainly make things easier.
I have very little experience with distributions/provisioning profiles unfortunately.

**Comment by PavelVanecek** [comment]
@Cykey could you please elaborate more on the impossibility? Enterprise app using MobileWiFi.framework is exactly what I would like to do.

**Comment by davidmurray** [comment]
I investigated it and from my understand it is not possible. Apple checks which entitlements you use when using a provisioning profile, therefore you cannot do it.
