### ISSUE TITLE
Need help for a newbie

### ISSUE THREAD

**Issue by kameshraj** [davidmurray/wifi#2]
Hi
I am trying to develop an app that can scan ssids and connect to them. I am learning theos and looked on the web for help and found this great project. I downloaded the source and tried to install it on my jail breaked 3GS running 6.1.3. I have xcode with 7.0 SDKs. 

I ran make package install and theos installed this app on my phone. But when i start this app it crashed immediately. I looked at the device log and found these lines. I also tried ldid /Application/WiFi.app/WiFi (suggested in previous post) it returned nothing

Could you please help what i am missing to get this working on the  phone?

Device Logs

---

Nov  6 10:18:49 test-iPhone login[1682] <Notice>: DEAD_PROCESS: 1682 ttys002
Nov  6 10:18:50 test-iPhone WiFi[1707] <Notice>: MS:Notice: Installing: me.cykey.wifi [WiFi](793.00)
Nov  6 10:18:50 test-iPhone WiFi[1707] <Notice>: MS:Notice: Loading: /Library/MobileSubstrate/DynamicLibraries/Activator.dylib
Nov  6 10:18:50 test-iPhone wifid[15] <Error>: WiFi:[405454730.664474]: kern_return_t _wifi_manager_open(mach_port_t, int, int, mach_port_t, mach_port_t *, audit_token_t) Client WiFi has no entitlement
Nov  6 10:18:50 test-iPhone WiFi[1707] <Error>: WiFi:[405454730.668074]: Failed to open connection to WiFi Manager kr=2
Nov  6 10:18:50 test-iPhone ReportCrash[1708] <Notice>: MS:Notice: Installing: (null) [ReportCrash](793.00)
Nov  6 10:18:51 test-iPhone ReportCrash[1708] <Notice>: Formulating crash report for process WiFi[1707]
Nov  6 10:18:51 test-iPhone com.apple.launchd[1](UIKitApplication:me.cykey.wifi[0xb3da][1707]) <Warning>: (UIKitApplication:me.cykey.wifi[0xb3da]) Job appears to have crashed: Segmentation fault: 11 
Nov  6 10:18:51 test-iPhone backboardd[1635] <Warning>: Application 'UIKitApplication:me.cykey.wifi[0xb3da]' exited abnormally with signal 11: Segmentation fault: 11 
Nov  6 10:18:51 test-iPhone ReportCrash[1708] <Error>: libMobileGestalt copySystemVersionDictionaryValue: Could not lookup ReleaseType from system version dictionary
Nov  6 10:18:51 test-iPhone ReportCrash[1708] <Notice>: Saved crashreport to /var/mobile/Library/Logs/CrashReporter/WiFi_2013-11-06-101850_test-iPhone.plist using uid: 0 gid: 0, synthetic_euid: 501 egid: 0

**Comment by davidmurray** [comment]
Hey there!

This issue is pretty easy to fix.

Can you tell me if you have ldid installed on your Mac?
You can d so by just running 'ldid' in Terminal and it says "command not found", that means that you don't have it installed.

**Comment by kameshraj** [comment]
Yeah I have ldid installed on my mac

Thanks

**Comment by davidmurray** [comment]
Alright, can you run `make; ldid -e ./obj/WiFi.app/WiFi` in your build directory?

**Comment by kameshraj** [comment]
Thank you, this is what i get

$ ldid -e ./obj/WiFi.app/WiFi
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "
http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>com.apple.wifi.manager-access</key>
        <true/>
    </dict>
</plist>
$

On Wed, Nov 6, 2013 at 3:13 PM, David M. notifications@github.com wrote:

> Alright, can you run ldid -e ./obj/WiFi.app/WiFi in your build directory?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cykey/wifi/issues/2#issuecomment-27923638
> .

## 

---

 __0/  "A ten thousand miles journey begins
   /_    with a single step. That single step
`\/  \,  has to be taken from where you are"

http://www.kameshraj.com

**Comment by davidmurray** [comment]
Hm, this is the expected output. :( Normally, when people are having that "missing entitlement" crash, it is because the app was not properly signed with the correct entitlements and wifid freaks out when the app tries to use some APIs.

Could you try installing this deb file instead? I just compiled the app. This way we'll find out if it's an issue in your build system or if it's an issue with your device. http://d.pr/f/hTad

**Comment by kameshraj** [comment]
Wow, thanks for the fast reply, really appreciate it.

Thanks for the .deb file, i can install it on my phone (copied to
/var/folder and installed it through iFile).
Now i can launch the app (yeah!) and see list off SSID's.
But the app crashes when i connected to an SSID (WPA)

As you guessed it looks like build system issue, could you give me
instructions on how do you build?

Thanks and Regards

crash log

---

Nov  6 17:14:59 test-iPhone WiFi[1908] <Notice>: MS:Notice: Installing:
me.cykey.wifi [WiFi](793.00)
Nov  6 17:14:59 test-iPhone WiFi[1908] <Notice>: MS:Notice: Loading:
/Library/MobileSubstrate/DynamicLibraries/Activator.dylib
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:01 test-iPhone WiFi[1908] <Warning>:
[DMNetwork]:[__25-[DMNetwork populateData]_block_invoke]: Error while
getting vendor: The Internet connection appears to be offline.
Nov  6 17:15:13 test-iPhone securityd[1909] <Notice>: MS:Notice:
Installing: (null) [securityd](793.00)
Nov  6 17:15:13 test-iPhone securityd[1909] <Error>: WiFi[1908]
SecItemCopyMatching: missing entitlement
Nov  6 17:15:13 test-iPhone securityd[1909] <Error>: WiFi[1908]
SecItemAdd: missing entitlement
Nov  6 17:15:13 test-iPhone wifid[15] <Error>: WiFi:[405479713.655249]:
No password for Guhamani2
Nov  6 17:15:13 test-iPhone ReportCrash[1911] <Notice>: MS:Notice:
Installing: (null) [ReportCrash](793.00)
Nov  6 17:15:13 test-iPhone kernel[0] <Debug>: 016468.545471
wlan.N[1418] AppleBCMWLANCore::setDISASSOCIATE():  [wifid]:
Nov  6 17:15:14 test-iPhone ReportCrash[1911] <Notice>: Formulating
crash report for process WiFi[1908]
Nov  6 17:15:14 test-iPhone com.apple.launchd[1](UIKitApplication:me.cykey.wifi[0x5171][1908]) <Warning>:
(UIKitApplication:me.cykey.wifi[0x5171]) Job appears to have crashed:
Segmentation fault: 11
Nov  6 17:15:14 test-iPhone backboardd[1635] <Warning>: Application
'UIKitApplication:me.cykey.wifi[0x5171]' exited abnormally with signal 11:
Segmentation fault: 11
Nov  6 17:15:14 test-iPhone ReportCrash[1911] <Error>: libMobileGestalt
copySystemVersionDictionaryValue: Could not lookup ReleaseType from system
version dictionary
Nov  6 17:15:15 test-iPhone ReportCrash[1911] <Notice>: Saved
crashreport to
/var/mobile/Library/Logs/CrashReporter/WiFi_2013-11-06-171513_test-iPhone.plist
using uid: 0 gid: 0, synthetic_euid: 501 egid: 0
Nov  6 17:16:04 test-iPhone securityd[1913] <Notice>: MS:Notice:
Installing: (null) [securityd](793.00)
Nov  6 17:16:04 test-iPhone crash_mover[1915] <Notice>: MS:Notice:
Installing: (null) [crash_mover](793.00)
Nov  6 17:16:04 test-iPhone dataaccessd[83] <Notice>: 0x1d54c7c0|DA|Note
|AccountID: 80E06C51-A7B7-49A4-BCFE-6120FC2BF014 ("Gmail") (Legacy)

**Comment by davidmurray** [comment]
Oh, whoops, my bad. I made a stupid mistake ;P

Here, try this one: http://d.pr/f/XYc9

As for my build process: I just run make really. Nothing fancy ;P. Perhaps it might be because you have an old version of ldid? Try compiling and installing ldid from http://gitweb.saurik.com/ldid.git

Thanks

**Comment by kameshraj** [comment]
This worked perfect. Thanks very much

I will debug to see what i am missing in my build environment. BTW what SDK
are you using? I am trying to build this with SDK 7.0

On Wed, Nov 6, 2013 at 5:38 PM, David M. notifications@github.com wrote:

> Oh, whoops, my bad. I made a stupid mistake ;P
> 
> Here, try this one: http://d.pr/f/XYc9
> 
> As for my build process: I just run make really. Nothing fancy ;P. Perhaps
> it might be because you have an old version of ldid? Try compiling and
> installing ldid from http://gitweb.saurik.com/ldid.git
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Cykey/wifi/issues/2#issuecomment-27931490
> .

## 

---

 __0/  "A ten thousand miles journey begins
   /_    with a single step. That single step
`\/  \,  has to be taken from where you are"

http://www.kameshraj.com

**Comment by davidmurray** [comment]
I am using the 6.1 SDK.

**Comment by kameshraj** [comment]
I tried with SDK 6.1 and it works good, complains with SDK 7.
Thanks
