### ISSUE TITLE
Wifi Scanning

### ISSUE THREAD

**Issue by santhuisland** [davidmurray/wifi#20]
Hi All,

Advance thanks for your help..
i am really want to fix this in my project. Please please help me

1)My application will not go to Appstore, it will be Enterprice app.
2)I want to trigger wifi scan programatically, nothing else.
3)where i can find private framework "MobileWiFi.framework" in Xcode 6.1?
4)I have included "WiFiDeviceClient.h,WiFiNetwork.h,WiFiManager.h,MobileWiFi.h"
5)I have include Entitlement.plist same has downloaded from this project. But getting following error 
"The entitlements specified in your application’s Code Signing Entitlements file do not match those specified in your provisioning profile. (0xE8008016)."
6)I need to jailbroke the device?
5) using following code
_manager = WiFiManagerClientCreate(kCFAllocatorDefault, 0);
CFArrayRef devices = WiFiManagerClientCopyDevices(_manager);
if (devices) {
_client = (WiFiDeviceClientRef)CFArrayGetValueAtIndex(devices, 0);
CFRetain(_client);
CFRelease(devices);
}
_networks = [[NSMutableArray alloc] init];
WiFiManagerClientScheduleWithRunLoop(_manager, CFRunLoopGetCurrent(), kCFRunLoopDefaultMode);
WiFiDeviceClientScanAsync(_client, (CFDictionaryRef)[NSDictionary dictionary], DMScanCallback, NULL);

Thanks
Santhosh

**Comment by davidmurray** [comment]
Will reply in the other issue.
