### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by cansurmeli** [davidmurray/wifi#25]
Hi.

I'm trying to compile(with theos) the code which relates to retrieving the list of known networks. I've added the reverse engineered libraries. But unfortunately I'm getting the following errors:

http://pastebin.com/jyCntdBa

How can I get around this issue?

p.s. My 'Entitlements.xml' is standing at the root of the directory which is copied from Cykey's 'Wi-Fi-scan' example project. Is something wrong with that?

**Comment by davidmurray** [comment]
This error:
`@UILabel *wifiSignalStrengthLabel;`
is not caused by my code. That '@' does not belong there.

Regarding the other errors: Your headers seem be to slightly "broken", you might have to fix your IOKit headers (try the ones from https://github.com/rpetrich/iphoneheaders).

Also, you need to link with MobileWiFi.framework. In your Makefile, add `YOUR-APP-NAME_PRIVATE_FRAMEWORKS = MobileWiFi`
To sign your apps with the entitlements, add `YOUR-APP-NAME_CODESIGN_FLAGS = -SEntitlements.xml`

Let me know if this works for you. Also note that those headers are GPL licensed, therefore any code that uses it must be open-source.

**Comment by cansurmeli** [comment]
All right, first off. That error was related to another compilation. Sorry about that typo.

My Makefile now is like the following:

http://pastebin.com/BxU9WT3Z

And my entitlements.xml is:

http://pastebin.com/ykDkw9LJ

I'm still getting the following errors when I run 'make package'. Although the .deb file is being generated but the binary crashes when run on the iPhone.

http://pastebin.com/WX61zsAF

It seems to me that my project goes looking for the Xcode headers but not the reverse engineered ones. Is this behaviour correct?

Also I've forgotten to mention that the device I'm only able to test the code is an iPhone 4 running iOS 7.

A detailed explanation will be much appreciated.

**Comment by davidmurray** [comment]
Where are your headers? Do you have anything in `$THEOS/include`?

Also, make sure that you have `ldid` installed. If you don't, do this:

```
git clone git://git.saurik.com/ldid.git
cd ldid
git submodule update --init
./make.sh
cp -f ./ldid $THEOS/bin/ldid
```

Thanks

**Comment by cansurmeli** [comment]
I only have these under `$THEOS/include`:

`DHCommon.h
DHHookCommon.h
logos
substrate.h`

Should I place the reverse engineered headers under `$THEOS/include`? I tried this, re-run `make package` and it was complaining about the same errors as before.

I've `ldid` listed under `$THEOS/bin`. When I was setting up Theos, I executed the command you've given. So `ldid` should be fine.

Thanks man 👍

**Comment by davidmurray** [comment]
Try adding all the headers from https://github.com/rpetrich/iphoneheaders in there as well as the reverse engineered MobileWiFi headers.

Also, run `make clean` before running `make package` to make sure that the compilation starts fresh.

**Comment by cansurmeli** [comment]
I sorted out my issues with my Theos installation and it's compiling just fine right now. If anyone else is having similar problems:
- use DHowett's dm.pl instead of dpkg,
- pass -Zlzma to dpkg as an argument,
- delete the Theos copy inside the Wi-Fi project of Cykey and create a symlink to your local one.

**Comment by leiyong316** [comment]
hi @cansurmeli  how to compile this project on IOS8?  can you help me.  very very thanks

**Comment by cansurmeli** [comment]
What are you experiencing exactly? @leiyong316
