### ISSUE TITLE
how to build this project?

### ISSUE THREAD

**Issue by leiyong316** [davidmurray/wifi#26]
Thanks

**Comment by davidmurray** [comment]
`make`

**Comment by leiyong316** [comment]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS8.3.sdk/usr/include/libkern/OSByteOrder.h:45:10: fatal error: 
      'libkern/machine/OSByteOrder.h' file not found
#include <libkern/machine/OSByteOrder.h>
         ^
8 errors generated.
 Compiling src/DMNetworksViewController.m...
src/DMNetworksViewController.m:390:23: error: class method
      '+imageNamed:inBundle:' not found (return type defaults to 'id')
      [-Werror,-Wobjc-method-access]
  ...image = [UIImage imageNamed:@"BlueCheck" inBundle:_airPortSettingsBundle];
                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/DMNetworksViewController.m:398:41: error: class method
      '+imageNamed:inBundle:' not found (return type defaults to 'id')
      [-Werror,-Wobjc-method-access]
  ...[[cell imageView] setImage:[UIImage imageNamed:@"spacer" inBundle:_airPo...
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
make[2]: **\* [obj/src/DMNetworksViewController.m.5c390147.o] Error 1
make[1]: **\* [internal-application-all_] Error 2
make: **\* [WiFi.all.application.variables] Error 2

**Comment by leiyong316** [comment]
How can I be,  do you have compile&install document

thanks

**Comment by leiyong316** [comment]
build Finished,   but running have a problem,  variable  devices  return NULL.
Environment  xcode6.3.1,  iphone4 IOS7,   no jailbreak,
How I need to do.
thanks

![image](https://cloud.githubusercontent.com/assets/2143362/7507375/3bd36b22-f4a1-11e4-9d21-41d479fd4df5.png)

**Comment by davidmurray** [comment]
I will gladly do paid consulting, but this is a free and open-source project, so you should try to figure out how to compile and use it. I'm sure it's not that difficult to fix those issues.

**Comment by leiyong316** [comment]
thanks,  I did it
