### ISSUE TITLE
A method error occured after the make command exectued when I build this project

### ISSUE THREAD

**Issue by leejunhui** [davidmurray/wifi#29]
Hello,When I want to build this project,I try to run `make`
,but got this error

![error](http://ww3.sinaimg.cn/large/c0644dbegw1ewybs0dskdj20y10esdng.jpg)
It seems the class method `imageNamd:inBundle:` is undefined.
And Then I  searched the development document of Apple.I've foudn this method

```
+ imageNamed:inBundle:compatibleWithTraitCollection:
```

But this method is released in iOS 8.0. So, I am wondering if this method is a private API? Or how can I build the project in another workaround. Hope you can see this issue, :)

**Comment by davidmurray** [comment]
Hm, the method is defined in `DMNetworksViewController.h`, so I'm not sure why the error happens.

In any case, try adding this at the top of the `Makefile`:

`export GO_EASY_ON_ME=1`

and then try running `make` again. Hopefully the error will turn into a warning and you'll be able to successfully build the project.

**Comment by leejunhui** [comment]
Appreciate! I've successfully done the steps of `make`,`make package`，and I put the`deb`file into the Cydia's `autointall` folder,and then reboot my iPhone.But when I launched the app, it just crashed immediately. Below is the devices logs :(My iPhone is iPhone 5s, iOS 8.4, already jailborken)
![Devices Logs](http://ww3.sinaimg.cn/large/c0644dbegw1ewys0jw6cij20ul0k4dur.jpg)
It seems like the cause of crash is `EXC_BAD_ACCESS`, I am a newbie of iOS Development, So I can not figure out how to fix that bug, hope you can help me, thanks!

-- update 
After I have search the closed issue 1, I have found the `ldid -e /Applications/WiFi.app/WiFi`,and then I done this.and it outputs `ldid.cpp(1188): _assert(signature != NULL); errno=0`

--update again
Hopefully,I've rebuild the project and install on my device.and when I type  `ldid -e /Applications/WiFi.app/WiFi` in the terminal, it outputs
![logs](http://ww4.sinaimg.cn/large/c0644dbegw1ewyttn0hj2j20qn07r76h.jpg)

--update again
I've successfully launched the app,awesome!
![screenshot](http://ww2.sinaimg.cn/large/c0644dbegw1ewytxancqhj20hs0vkq3e.jpg)

**Comment by leejunhui** [comment]
I have build the project successfully on Xcode, thanks a lot for your help! Enjoy the good day!

**Comment by davidmurray** [comment]
I'm glad that you've been able to solve the issue(s)!

Thanks,
David
