### ISSUE TITLE
Error in DMNetworksManager.m

### ISSUE THREAD

**Issue by kameshraj** [davidmurray/wifi#3]
Hi
I downloaded the latest files and tried to build it. I got this error message

$ make
/Users/test/wifi-master/theos/makefiles/targets/Darwin/iphone.mk:41: Deploying to iOS 3.0 while building for 6.0 will generate armv7-only binaries.
Making all for application WiFi...
 Copying resource directories into the application wrapper...
 Compiling src/DMDetailViewController.m...
 Compiling src/DMInformationViewController.m...
 Compiling src/DMNetwork.m...
 Compiling src/DMNetworksManager.m...
cc1obj: warnings being treated as errors
src/DMNetworksManager.m: In function ‘-[DMNetworksManager removeNetwork:]’:
src/DMNetworksManager.m:159: warning: implicit declaration of function ‘WiFiManagerClientRemoveNetwork’
make[2]: **\* [obj/src/DMNetworksManager.m.5505afcb.o] Error 1
make[1]: **\* [internal-application-all_] Error 2
make: **\* [WiFi.all.application.variables] Error 2
$

If i comment out the line 159. The app builds and installs on my device. Also this work only woth SDK 6.0 and fails under 6.1 (want to make sure i am using right versions)

Thanks

**Comment by davidmurray** [comment]
Sorry, I fixed it. Reclone or git pull and update the submodules.
