### ISSUE TITLE
could you make a class easy to use WiFiManager like WifiScanner ?

### ISSUE THREAD

**Issue by GF-Huang** [davidmurray/wifi#5]
Make a class is easy to use and use in the .ipa not the .deb , such as this class https://github.com/ipinak/iOS-WiFi/tree/master/iOS-WiFi.  But it's not sopport at ios 7. 
Thanks you !

**Comment by davidmurray** [comment]
I don't understand.

**Comment by GF-Huang** [comment]
my device was jailbreak.  can i use the WifiManager in app, not in tweak ?

**Comment by davidmurray** [comment]
You want to install my wifi app but you're not sure how?

**Comment by GF-Huang** [comment]
no. i want use the DMNetworksManager class in my app.

**Comment by davidmurray** [comment]
So what's the problem? Can you be a little more specific?
