### ISSUE TITLE
Why the WiFiManagerClientCopyDevices return 0x0 ?

### ISSUE THREAD

**Issue by GF-Huang** [davidmurray/wifi#7]
i use your class in my project.
and the WiFiManagerClientCopyDevices return 0x0.
help, please

![image](https://f.cloud.github.com/assets/4510984/2480459/a97cc250-b0bd-11e3-913b-f434c5236fe3.png)
![image](https://f.cloud.github.com/assets/4510984/2480462/c3823aa4-b0bd-11e3-836d-b56df664a4f2.png)

**Comment by davidmurray** [comment]
Are you sure that your application has the `com.apple.wifi.manager-access` entitlement?

**Comment by GF-Huang** [comment]
sorry, what's the meaning of "com.apple.wifi.manager-access" ? 
My app is a normal app, not the cydia app, but my device was jailbreak.

**Comment by davidmurray** [comment]
Your application needs to be signed with a custom entitlement (com.apple.wifi.manager-access). I'm sure that there are plenty of tutorials that show how to do this.

**Comment by GF-Huang** [comment]
oh, my god. if need to resign , how can i debug my app with xcode. But, Thank you !

**Comment by davidmurray** [comment]
Xcode isn't really meant to do jailbreak stuff. It'll cause you some trouble along the way.

**Comment by GF-Huang** [comment]
great, i resign my app success ! 
1. The Bulid setting set don't code sign, then build.
2. use ldid to resign my app with "entitlements.xml" 
3. run with xcode.

but there's a new problem, my app run success and got wifi info, but xcode can't debug the program, breakpoint no trigger.

i want debug the app with xcode,  can you help me ?

![image](https://f.cloud.github.com/assets/4510984/2490933/1d433026-b1d0-11e3-96a1-4d8e9593c08e.png)

![64d93d94-ab53-44b1-8067-4181e531deb1](https://f.cloud.github.com/assets/4510984/2490907/ec61e440-b1cd-11e3-8598-135651ddff03.png)

**Comment by davidmurray** [comment]
Hm, that's odd. I have no idea what's wrong. Really though, when you're building jailbreak stuff Xcode will get in your way. Perhaps you should use theos?

**Comment by GF-Huang** [comment]
is there any other way to debug this kind of app ?

**Comment by GF-Huang** [comment]
great, i find a good way to debug app  with xcode and resign for use private framework.

![image](https://f.cloud.github.com/assets/4510984/2491029/15013f5a-b1d7-11e3-9906-4526e571dba5.png)

now, set the code signing entitlements value to the path of  entitlements.xml in this project.
![image](https://f.cloud.github.com/assets/4510984/2491035/7f7b1f22-b1d7-11e3-978f-a5c952532dfe.png)

bulid and enjoy it !

**Comment by davidmurray** [comment]
So everything works now?

**Comment by GF-Huang** [comment]
yes, works well.

**Comment by santhuisland** [comment]
we need to jailbroke the device if i want to use this "com.apple.wifi.manager-access" in entitlements?

**Comment by davidmurray** [comment]
Yes.

**Comment by leiyong316** [comment]
I added "code signing entitlements"  this error.
can you help me? 
thanks

![image](https://cloud.githubusercontent.com/assets/2143362/7509768/9822cfe6-f4c7-11e4-9aed-c1a3bf415533.png)

**Comment by davidmurray** [comment]
You can't sign your app with that entitlement when using a provisioning profile. It's not possible; Apple does not allow it.

**Comment by leiyong316** [comment]
@Cykey  I found the cause of the problem, device need to jailbreak.
