### ISSUE TITLE
About some API effect

### ISSUE THREAD

**Issue by GF-Huang** [davidmurray/wifi#8]
What can the following APIs do ? 
I don't understand for their names.
Can you tell me? please.

```
    void WiFiManagerClientSetMISState(WiFiManagerRef manager, int state);
void WiFiManagerClientSetMisPassword(WiFiManagerRef manager, CFStringRef password);
void WiFiManagerClientSetMISDiscoveryState(WiFiManagerRef manager, int state);

int WiFiManagerClientGetMISState(WiFiManagerRef manager);
int WiFiManagerClientGetMISDiscoveryState(WiFiManagerRef manager);

    void WiFiDeviceClientRegisterLQMCallback(WiFiDeviceClientRef device, WiFiDeviceClientCallback callback, const void *object);
    void WiFiDeviceClientRegisterExtendedLinkCallback(WiFiDeviceClientRef device, WiFiDeviceClientCallback callback, const void *object);
    void WiFiDeviceClientRegisterLinkCallback(WiFiDeviceClientRef device, WiFiDeviceClientLinkCallback callback, const void *object);
```

**Comment by davidmurray** [comment]
The `MIS` functions are for internet tethering.

The `Register` functions are used to set up a callback function when one of the actions happen.

WiFiDeviceClientRegisterLQMCallback is used to setup a callback function for when the signal strength changes. WiFiDeviceClientRegisterLinkCallback is for when you connect or disconnect from a WiFi network, I believe.

**Comment by GF-Huang** [comment]
oh, I see, thank you .  But there's a little problem.  I know the wifi password, i use the following code to join the wifi
        self.network.password = inputTextField.text;
        [[DMNetworksManager sharedInstance] associateWithNetwork:self.network];

but join fail.  And I use the Setting -> wi-fi to join to join, Success.

**Comment by davidmurray** [comment]
There should be some logs in the syslog when joining a network fails, if I recall correctly.
